from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.ingestion.embedder import Embedder
from app.models.chunk import Chunk


class ChunkIndexer:
    """
    Stores document chunks and their embeddings in PostgreSQL.

    Flow:
        chunks
          ↓
        Embedder
          ↓
        embeddings
          ↓
        file_chunks
    """

    def __init__(
        self,
        db: AsyncSession,
        embedder: Embedder,
    ) -> None:
        self.db = db
        self.embedder = embedder

    async def index_chunks(
        self,
        file_id: UUID,
        chunks: list[str],
        metadata: list[dict[str, Any]] | None = None,
    ) -> list[Chunk]:
        """
        Generate embeddings and store chunks.

        Args:
            file_id: ID of the file being indexed.
            chunks: Text chunks generated by chunker.py.
            metadata: Optional metadata for each chunk.
        """

        if not chunks:
            return []

        metadata = metadata or [{} for _ in chunks]

        if len(metadata) != len(chunks):
            raise ValueError(
                "metadata length must match chunks length"
            )

        # Remove empty chunks.
        valid_chunks = [
            (index, text.strip(), metadata[index])
            for index, text in enumerate(chunks)
            if text and text.strip()
        ]

        if not valid_chunks:
            return []

        texts = [
            text
            for _, text, _ in valid_chunks
        ]

        # Generate embeddings in one API request.
        embeddings = await self.embedder.embed_texts(texts)

        if len(embeddings) != len(texts):
            raise RuntimeError(
                "Embedding count does not match chunk count."
            )

        indexed_chunks: list[Chunk] = []

        for (
            embedding_index,
            (original_index, content, chunk_metadata),
        ) in enumerate(valid_chunks):

            chunk = Chunk(
                file_id=file_id,
                chunk_index=original_index,
                content=content,
                embedding=embeddings[embedding_index],
                metadata_=chunk_metadata,
            )

            self.db.add(chunk)
            indexed_chunks.append(chunk)

        await self.db.flush()

        return indexed_chunks

    async def delete_file_chunks(
        self,
        file_id: UUID,
    ) -> int:
        """
        Delete all indexed chunks belonging to a file.

        Useful when a file is deleted or re-indexed.
        """

        result = await self.db.execute(
            select(Chunk).where(
                Chunk.file_id == file_id
            )
        )

        chunks = result.scalars().all()

        for chunk in chunks:
            await self.db.delete(chunk)

        await self.db.flush()

        return len(chunks)